version: '3'

services:
  notification_api:
    image: bhavesh2781993/digiborn-notification-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:9090
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
      - EMAIL_SERVER_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_SERVER_PORT=587
      - EMAIL_USERNAME=test_username
      - EMAIL_PASSWORD=test_password
  postgresql_db:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notificationdb
      - POSTGRES_USER=notification-api
      - POSTGRES_PASSWORD=notification
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres_data: