spring.application.name: notification-api

# Email Server Configurations
spring.mail:
  host: ${EMAIL_SERVER_HOST}
  port: ${EMAIL_SERVER_PORT}
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  properties:
    mail.smtp:
      auth: true
      starttls.enabled: true

# Database Connection
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_SCHEMA}?prepareThreshold=0
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}


# Data Migration
spring.flyway:
  enabled: true
  locations: classpath:db/migration/{vendor}