spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

spring.mail:
  host: sandbox.smtp.mailtrap.io
  port: 587
  username: 1
  password: 1
  properties:
    mail.smtp:
      auth: true
      starttls.enabled: true

notification:
  email:
    from: test@gmail.com

