<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Learning how to code an HTML email</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div style="margin-top: 10px">Greetings, ${name}</div>
    <div>Your username is <b>${name}</b></div>
    <br/>
    <div> Have a nice day..!</div>
</body>
</html>